---
title: "Manualpin_boxplots"
author: "Becca Morris"
date: "2024-05-02"
output: html_document
---


```{r setup, include=FALSE}

library(readxl)
library(tidyverse)
library(dplyr)
library(ggrepel)

```

```{r}
setwd("~/GitHub/BeccaTransects/data")
sedpindata <- read_xlsx("Sediment_Pin_Data.xlsx", sheet = "All_Data") #I remove the ref pins in the df code
```
#set up the color-blind color palette
```{r}
cbpsed <- c("#0072B2","#E69F00","#D55E00","#009E73", "#56B4E9", "#000000", "#CC79A7", "#F0E442")
```
#prepping the dataframe
```{r}
sedpins <- sedpindata %>% 
  filter(Month != "April") %>% #removed April measurements so that these will be more consistent with RTK June starting point
  mutate(Date = paste0(Year, "-", Month)) %>% #make new column combining year and month into date
  
  filter(!(Pin_ID == "C6-BW174" & Date == "2022-June")) %>% #this was a huge outlier so I removed it
  mutate_at(c('Upper', 'Middle','Lower'), as.numeric) %>% #make Upper and Middle columns numeric (have NA's)
  select(-c("Notes")) %>% #remove "Notes" column
  mutate(across(where(is.numeric), ~round(., 1))) %>%  #round values to one decimal point
  group_by(Pin_ID, Shoreline_End) %>% 
  rename(Transect_ID = Pin_ID)
#arrange(Date, .by_group = TRUE) %>% 


sedpinmetadata <- read_xlsx("~/GitHub/BeccaTransects/data/Sediment_Pin_Data.xlsx", sheet = "Metadata")

#Since sedpins df (above already has a "Shoreline_End" column we need to remove this column form the veg meta data sheet so that there aren't issues merging two df's with the same column names

sedpinmetadata <-select(sedpinmetadata, -c("Shoreline_End"))


SedPinDataMerged <- full_join(sedpins, sedpinmetadata, by = "Transect_ID")
```

## Setting up df for EvW *AND* Log v No Log:
```{r}
sedpinchangeLvNL <- SedPinDataMerged[SedPinDataMerged$Log_Presence != "reference",] %>% 
  select(Transect_ID, Shoreline_End, Upper, Middle, Lower, Date, Log_Presence) %>% 
  mutate(UpperDiff = (last(Upper) - first(Upper))*-1) %>% 
  mutate(MiddleDiff = (last(Middle) - first(Middle))*-1) %>% 
  mutate(LowerDiff = (last(Lower) - first(Lower))*-1) %>% 
  select(-c('Date', 'Upper', 'Middle', 'Lower')) %>% #remove all unnecessary columns
  distinct() %>%  #this removes repeated values for each month's calculation
  pivot_longer(UpperDiff:LowerDiff, names_to = "Pin_Location", values_to = "Sediment_Change") %>%
  rename(Zone = Pin_Location) %>% 
  mutate(Shoreline_End = factor(Shoreline_End, levels = c("west", "east")),
         Zone = factor(Zone, levels = c("UpperDiff", "MiddleDiff", "LowerDiff"))) %>% #this puts west first in the legend
  group_by(Log_Presence, Shoreline_End, Zone) %>% 
  #summarize(mean_difference = mean(Sediment_Change, na.rm = TRUE),
  #          sd_difference = sd(Sediment_Change, na.rm = TRUE),
  #          n_difference = n()) %>% 
  #mutate(se_difference = sd_difference/sqrt(n_difference)) %>% 
  mutate(across(where(is.numeric), ~round(., 1)))
```

```{r}
sedpinchangeLvNL_box <- ggplot(sedpinchangeLvNL,
                                  mapping = aes(x = Zone,
                                  y = Sediment_Change,
                                  #group = Log_Presence,
                                  fill = Log_Presence,
                                  color = log_Presence)) +
  geom_boxplot(position = position_dodge(0.55),color = "black", width = 0.50) +
  geom_hline(yintercept=0, linetype="dashed", color = "black") +
  scale_fill_manual(values = cbpsed) +
  facet_grid(~ Shoreline_End) +
  coord_cartesian(ylim = c(-25, 20)) + #sets the limit of the y-axis to show a more dramatic difference bw variables
  scale_x_discrete(labels = c(UpperDiff = "Upper", MiddleDiff = "Middle", LowerDiff = "Lower")) +
  labs(
    title = "Manual Measurement: Change in Sediment Pin Length ",
    subtitle = "From Jun 2022 to Sep 2023   (Positive value = accretion   Negative value = erosion)",
    y = "Change in Pin Length (cm)",
    x = "Marsh Zone",
    fill= "Log Presence",
    tag = "Manualpin_boxplots.Rmd_sedpinchangeLvNL_box",
    caption = "*n=10 west/log, n=7 west/no log, n=12 east/log, n=9 east/no log") +
  theme_bw(base_size = 10) +
  theme(axis.title = element_text(face = "bold", size=13),
        legend.title = element_text(face = "bold", size=09),
        legend.text=element_text(size=09),
        legend.position = "top",   #for no legend type: "none"
        legend.background = element_rect(fill="lightgrey",
                                  size=0.5, linetype="solid", 
                                  colour ="darkgrey"),
        axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(size = 09),
        plot.subtitle = element_text(size = 11),
        plot.tag = element_text(size = 6, angle = 90),
        plot.tag.position = "right",
        strip.text = element_text(size = 13, color = "black"))
  
  

sedpinchangeLvNL_box
#Will say: Warning: Removed 3 rows containing non-finite outside the scale range (`stat_boxplot()`). This is due to having NA's for a few of the pins.  
```


#EvW with Log varible
```{r}
sedpinchangeEvWandLvNL_box <- ggplot(sedpinchangeLvNL,
                                  mapping = aes(x = Zone,
                                  y = Sediment_Change,
                                  #group = Log_Presence,
                                  fill = Shoreline_End,
                                  color = Shoreline_End)) +
  geom_boxplot(position = position_dodge(0.55),color = "black", width = 0.50) +
  geom_hline(yintercept=0, linetype="dashed", color = "black") +
  scale_fill_manual(values = cbpsed) +
  facet_grid(~ Log_Presence) +
  coord_cartesian(ylim = c(-25, 20)) + #sets the limit of the y-axis to show a more dramatic difference bw variables
  scale_x_discrete(labels = c(UpperDiff = "Upper", MiddleDiff = "Middle", LowerDiff = "Lower")) +
  labs(
    title = "Manual Measurement: Change in Sediment Pin Length ",
    subtitle = "From Jun 2022 to Sep 2023   (Positive value = accretion   Negative value = erosion)",
    y = "Change in Pin Length (cm)",
    x = "Marsh Zone",
    fill= "End of Shoreline",
    tag = "Manualpin_boxplots.Rmd_sedpinchangeEvWandLvNL_box",
    caption = "*n=10 west/log, n=7 west/no log, n=12 east/log, n=9 east/no log") +
  theme_bw(base_size = 10) +
  theme(axis.title = element_text(face = "bold", size=13),
        legend.title = element_text(face = "bold", size=09),
        legend.text=element_text(size=09),
        legend.position = "top",   #for no legend type: "none"
        legend.background = element_rect(fill="lightgrey",
                                  size=0.5, linetype="solid", 
                                  colour ="darkgrey"),
        axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(size = 09),
        plot.subtitle = element_text(size = 11),
        plot.tag = element_text(size = 6, angle = 90),
        plot.tag.position = "right",
        strip.text = element_text(size = 13, color = "black"))
  
  

sedpinchangeEvWandLvNL_box
```


#Now make boxplot for EvW with no log variable:
```{r}
sedpinchange <- SedPinDataMerged[SedPinDataMerged$Log_Presence != "reference",] %>%   
  mutate(UpperDiff = (last(Upper) - first(Upper))*-1) %>% 
  mutate(MiddleDiff = (last(Middle) - first(Middle))*-1) %>% 
  mutate(LowerDiff = (last(Lower) - first(Lower))*-1) %>% 
  #mutate(UpperDiff = ifelse(is.na(UpperDiff) & Pin_ID == "C1-BW6", 3.2, UpperDiff)) %>% 
  #mutate(UpperDiff = ifelse(is.na(UpperDiff) & Pin_ID == "C1-L5", 3.2, UpperDiff)) %>%
  select(-c('Month',`Month_#`, 'Year', 'Date', 'Upper', 'Middle', 'Lower')) %>% #remove all unnecessary columns
  distinct() %>%  #this removes repeated values for each month's calculation
  pivot_longer(UpperDiff:LowerDiff, names_to = "Pin_Location", values_to = "Sediment_Change") %>% 
  rename(Zone = Pin_Location) %>% 
  mutate(Shoreline_End = factor(Shoreline_End, levels = c("west", "east")),
         Zone = factor(Zone, levels = c("UpperDiff", "MiddleDiff", "LowerDiff"))) %>%
  group_by(Shoreline_End, Zone) #%>% 
  #summarize(mean_difference = mean(Sediment_Change, na.rm = TRUE),
  #          sd_difference = sd(Sediment_Change, na.rm = TRUE),
  #          n_difference = n()) %>% #n should be 18 for west UpperDiff
  #mutate(se_difference = sd_difference/sqrt(n_difference)) %>% 
  #mutate(across(where(is.numeric), ~round(., 1))) 
```

```{r}
sedpinchangeEvW_box <- ggplot(sedpinchange,
                                  mapping = aes(x = Zone,
                                  y = Sediment_Change,
                                  fill = Shoreline_End,
                                  color = Shoreline_End)) +
  geom_boxplot(position = position_dodge(0.55),color = "black", width = 0.50) +
  geom_hline(yintercept=0, linetype="dashed", color = "black") +
  scale_fill_manual(values = cbpsed) +
  coord_cartesian(ylim = c(-25, 20)) + #sets the limit of the y-axis to show a more dramatic difference bw variables
  scale_x_discrete(labels = c(UpperDiff = "Upper", MiddleDiff = "Middle", LowerDiff = "Lower")) +
  labs(
    title = "Manual Measurement: Change in Sediment Pin Length ",
    subtitle = "From Jun 2022 to Sep 2023   (Positive value = accretion   Negative value = erosion)",
    y = "Change in Pin Length (cm)",
    x = "Marsh Zone",
    fill= "End of Shoreline",
    tag = "Manualpin_boxplots.Rmd_sedpinchangeEvW_box",
    caption = "*n=10 west/log, n=7 west/no log, n=12 east/log, n=9 east/no log") +
  theme_bw(base_size = 10) +
  theme(axis.title = element_text(face = "bold", size=13),
        legend.title = element_text(face = "bold", size=09),
        legend.text=element_text(size=09),
        legend.position = "top",   #for no legend type: "none"
        legend.background = element_rect(fill="lightgrey",
                                  size=0.5, linetype="solid", 
                                  colour ="darkgrey"),
        axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(face = "bold", size = 14),
        plot.caption = element_text(size = 09),
        plot.subtitle = element_text(size = 11),
        plot.tag = element_text(size = 6, angle = 90),
        plot.tag.position = "right",
        strip.text = element_text(size = 13, color = "black"))
  
  

sedpinchangeEvW_box
```