---
title: "Veg Beta Diversity"
author: "Becca Morris"
date: "2024-02-27"
output: html_document
---

```{r}
library(adespatial)
library(ade4)
library(readxl)
library(tidyverse)
library(dplyr)
```

#load in the data
```{r}
setwd("~/GitHub/BeccaTransects/data")

vegmetadata <- read_xlsx("~/GitHub/BeccaTransects/data/VegData_raw.xlsx", sheet = "Metadata")
vegdata <- read_xlsx("~/GitHub/BeccaTransects/data/VegData_raw.xlsx", sheet = "Data_2")
```
# 1. creating the main data frame:
```{r}
VegDataNew <- vegdata %>% 
  mutate_at(c('MeIn', 'DiGr', 'RaSa', 'CaMa', 'SaSo', 'Lolium', 'FrSa', 'Fabiaceae','Vicia', 'Sonc', 'Xant', 'LeTr', 'Ranunculus', 'Taraxacum', 'Coytote_Bush','BoMa', 'DiSp', 'AtPx', 'PoAr', 'AcMa', 'GrSt', 'MixedSeedlings','GrGR', 'Melilotus', 'MePo'), as.numeric) %>% 
  mutate_if(is.numeric, list(~replace_na(., 0))) %>%
  select(-BaGr_Type_1, -BaGr_Type_2, -Coytote_Bush, -Wrack, -Tot_Num_Species, -Shoot_Density, -Length_centimeters, -Patch_Type) %>% 
  mutate(SaSp = SaPa + SaDe) %>% 
  mutate(SaPa_new = SaPa + ((SaPa/SaSp)*PicklePups)) %>%      #combine and distribute picklepup category amongst the two species
  mutate(SaDe_new = SaDe + ((SaDe/SaSp)*PicklePups)) %>% 
  mutate(across(c('SaPa_new', 'SaDe_new'),(~replace_na(., 0)))) %>%   #where the calculations above = 0, R was turning them into NaN's
  mutate(across(c('SaPa_new', 'SaDe_new'), ~round(., 0))) %>% 
  mutate(SaPa_new = if_else(SaPa_new > 25, 25, SaPa_new),
         SaDe_new = if_else(SaDe_new > 25, 25, SaDe_new)) %>% 
  mutate(Grass = GrGR + LeTr + MixedSeedlings) %>% 
  mutate(BaGr = rowSums(across(BaGr_1:BaGr_2), na.rm = T)) %>% 
  select(-BaGr_1, -BaGr_2) %>% 
  mutate(Total_Veg = 25-BaGr) %>%  #Total_Veg is simply what is remaining after subtracting the bare ground
  #mutate(across(SpFo:Total_Veg, ~ .x*4)) %>%  #makes percentages out of the counts
  mutate(across(everything(), ~replace(.x, is.nan(.x), 0))) %>%
  select(-c('GrGR','LeTr','MixedSeedlings','PicklePups', 'SaPa','SaDe', 'SaSp')) %>%  #removed SaSp so it would not be calculated as total veg in addition tot he SaPa and SaDe columns)) %>% 
  rename(SaPa = SaPa_new, SaDe = SaDe_new) %>% #putting their original names back after the calculation above
  mutate(Total_Veg2 = rowSums(across(SpFo:Grass), na.rm =T)) %>% #Total_Veg2 adds all the total quadrants each species is present in and combining them all into one total count (can exceed 100)
  mutate(Date = paste0(Year, "-", Month))  
```
#I want to clean up the metadata sheet:
```{r}
vegmetadata %>% 
  select(Transect_ID, Shoreline_End, Log_Presence) 
```

#I want to combine the veg data and veg metadata df's togetherand remove the extranneous columns:
```{r}
VegDataMerged <- full_join(VegDataNew, vegmetadata, by = "Transect_ID") %>% 
  select(-c(...9:...12)) 
  
```

#Now I will seperate my data up by zone:  *We removed the row where C6-L174 is equal to quadrat 3 and zone U since it was a big outlier.
```{r}
VegDataSpecies_U <- VegDataMerged[VegDataMerged$Date == "2022-June" & VegDataMerged$Zone == "U" &
                             !(VegDataMerged$Transect_ID == "C6-L174" & VegDataMerged$Quadrat == 3 & VegDataMerged$Zone == "U"),
                             c(3, 7:34)]

VegDataID_U <- VegDataMerged[VegDataMerged$Date == "2022-June" & VegDataMerged$Zone == "U",
                             #!(VegDataMerged$Transect_ID == "C6-L174" & VegDataMerged$Quadrat == 3 & VegDataMerged$Zone == "U"),
                           c('Transect_ID', 'Distance_meters', 'Quadrat', 'Zone', 'Date', 'Shoreline_End', 'Log_Presence')]

```

```{r}
VegDataSpecies_M <- VegDataMerged[VegDataMerged$Date == "2022-June" & VegDataMerged$Zone == "M",
                           c(3, 7:34)]

VegDataID_M <- VegDataMerged[VegDataMerged$Date == "2022-June" & VegDataMerged$Zone == "M",
                             #!(VegDataMerged$Transect_ID == "C6-L174" & VegDataMerged$Quadrat == 3 & VegDataMerged$Zone == "U"),
                           c('Transect_ID', 'Distance_meters', 'Quadrat', 'Zone', 'Date', 'Shoreline_End', 'Log_Presence')]
```

```{r}
VegDataSpecies_L <- VegDataMerged[VegDataMerged$Date == "2022-June" & VegDataMerged$Zone == "L",
                           c(3, 7:34)]

VegDataID_L <- VegDataMerged[VegDataMerged$Date == "2022-June" & VegDataMerged$Zone == "L",
                             #!(VegDataMerged$Transect_ID == "C6-L174" & VegDataMerged$Quadrat == 3 & VegDataMerged$Zone == "U"),
                           c('Transect_ID', 'Distance_meters', 'Quadrat', 'Zone', 'Date', 'Shoreline_End', 'Log_Presence')]
```

#Calculate beta diversity components for Jaccard
```{r}
veg.bd.j <- beta.div.comp(VegData_U, coef = "J", quant = T)

```

